server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice1_users
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  jwt:
    key:
      private: ${jwtKey}
    user:
      generator: ${userGenerator}
